### PR TITLE
fix: fix lint errors in utils

### LINKED ISSUE #700: Fix lint errors in utils

### PR DESCRIPTION
**Pull request by brianacnguyen**
## **Description**
- This PR fixes linting error in util files

## **Related issues**

Fixes: #700 

## **Manual testing steps**

1. Go to utils folder and checkout `getCSSVariablesFromStylesheet.ts` and `useJsonColor.ts`
2. Observe linting error
3.

### **Before**
Screenshot 2024-05-22 at 5 06 14 PM
Screenshot 2024-05-22 at 5 06 33 PM
Screenshot 2024-05-22 at 5 06 37 PM

### **After**
Screenshot 2024-05-22 at 5 06 21 PM
Screenshot 2024-05-22 at 5 09 04 PM

Function still works
Screenshot 2024-05-22 at 5 07 17 PM
Screenshot 2024-05-22 at 5 07 25 PM

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by garrettbear — APPROVED** [review]

File: docs/utils/getCSSVariablesFromStylesheet.ts [hunk 1]
```diff
@@ -22,12 +22,20 @@ export const getCSSVariablesFromStylesheet = (varPrefix: string): Color => {
...
+            '; Error: ',
+            err.message,
+          );
+        } else {
+          console.error(
+            'Access denied to stylesheet: ',
+            styleSheet.href,
+            '; Unknown error occurred.',
+          );
+        }
```
Comment (georgewrmarshall) [inline docs/utils/getCSSVariablesFromStylesheet.ts:38]: So this checks if the `err` is an instance of the javascript `Error` object otherwise it logs as unknown?

File: docs/utils/useJsonColor.ts [hunk 2]
```diff
@@ -68,20 +68,23 @@ export const useJsonColor = (): CompiledColors => {
...
               value: resolvedValue,
               description:
                 description + (value === resolvedValue ? '' : ` ${value}`),
             };
+            tempThemeColorPalette[shade] = tempShadeColor;
           });
+          tempThemeColors[colorName] = tempThemeColorPalette;
         });
+        compiledColors[themeName] = tempThemeColors;
       });
```
Comment (georgewrmarshall) [inline docs/utils/useJsonColor.ts:88]: Nice work! We might consider updating this function to be recursive in the future to better handle complex JSON structures, rather than using multiple forEach loops. We can revisit this enhancement later. 😅

**Review by georgewrmarshall — APPROVED** [review]
At the limit of my TypeScript knowledge but LGTM!

File: docs/utils/getCSSVariablesFromStylesheet.ts (hunk 1 above)
Comment (brianacnguyen) [reply docs/utils/getCSSVariablesFromStylesheet.ts:38]: yeah this is to get around the error `'err' is of type 'unknown'`

File: docs/utils/useJsonColor.ts (hunk 2 above)
Comment (brianacnguyen) [reply docs/utils/useJsonColor.ts:88]: yup
